### PR TITLE
Added support for polyhedral regions.

### PR DESCRIPTION
**Pull request by TomyLobo**
I hope this compiles :)

The according WorldEdit build: http://builds.enginehub.org/job/worldedit/2501/

### CODE REVIEW

**Comment by kenzierocks** [comment]
Can we get this merged? I'd like to have this support.

**Comment by Mumfrey** [comment]
It was merged 18 months ago! I just didn't use git at the time and didn't know about merging with git so I did it the subversion way which didn't close this issue.

**Comment by kenzierocks** [comment]
Oh, in that case I'll open up a bug.

**Comment by Mumfrey** [comment]
It works fine for me:

**Pull request closed without merging**
